# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-19 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_authors_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='dest',
        ),
        migrations.AddField(
            model_name='books',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
