# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-21 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_auto_20190221_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
